import asyncio
import json
import logging
import re
from collections.abc import AsyncIterator, Sequence

import httpx

from app.core.config import settings
from app.services.web_search import search_web_knowledge, should_trigger_search

logger = logging.getLogger(__name__)

ERUMI_SYSTEM_PROMPT = {
    "role": "system",
    "content": (
        "Bạn là Erumi - Trợ lý Trí tuệ Nhân tạo thông minh, sắc sảo, tự nhiên và đáng tin cậy.\n\n"
        "Nguyên tắc giao tiếp quan trọng nhất:\n"
        "1. Tự nhiên & linh hoạt: Tuyệt đối KHÔNG xem mọi tin nhắn là câu hỏi, KHÔNG dùng các câu sáo rỗng như 'Về câu hỏi của bạn...', 'Tôi đã hiểu câu hỏi của bạn...', 'Erumi đã ghi nhận...'.\n"
        "2. Cung cấp dữ liệu thực tế: Khi người dùng hỏi về trường học, liên thông, tuyển sinh, địa lý, chính sách hay sự kiện: Hãy trả lời đầy đủ, chi tiết, có danh sách rõ ràng các trường, mốc thời gian và điều kiện cụ thể. Tuyệt đối KHÔNG từ chối hay bảo người dùng tự tìm trên mạng.\n"
        "3. Xử lý phản biện & tranh luận ('sai rồi', 'chưa đúng', v.v.):\n"
        "   - Hãy xem lại ngữ cảnh trước đó một cách bình tĩnh, logic và tự tin.\n"
        "   - Nếu câu trả lời trước đó là chân lý/toán học hiển nhiên (ví dụ 1 + 1 = 2): Hãy giữ vững lập trường một cách lịch thiệp, thông minh và hóm hỉnh.\n"
        "   - Nếu bạn thực sự có nhầm lẫn hoặc thiếu sót: Hãy chân thành tiếp thu và đưa ra thông tin chuẩn xác ngay lập tức.\n"
        "4. Chủ quyền lãnh thổ Việt Nam: Quần đảo Hoàng Sa và Trường Sa luôn là một phần lãnh thổ thiêng liêng, không thể tách rời của nước Cộng hòa Xã hội Chủ nghĩa Việt Nam (UNCLOS 1982).\n"
        "5. Ngôn ngữ: Sử dụng tiếng Việt chuẩn mực, thông minh, mượt mà và tinh tế."
    ),
}


def clean_refusal_prefix(text: str) -> str:
    """Strip apologetic refusal preambles if generated by base model."""
    patterns = [
        r"^(?:Xin lỗi|Rất tiếc)[^.\n]*?(?:không thể|chưa thể)[^.\n]*?(?:trực tuyến|ngay lập tức|chi tiết|như bạn yêu cầu)[^.\n]*?[.:\n]+(?:\s*(?:Tuy nhiên|Mặc dù vậy)[^.\n]*?[.:\n]+)?",
        r"^(?:Xin lỗi|Rất tiếc)[^.\n]*?[.:\n]+",
        r"^(?:Với tư cách là|Là một)[^.\n]*?[.:\n]+",
    ]
    res = text
    for p in patterns:
        res = re.sub(p, "", res, flags=re.IGNORECASE).strip()
    return res


def generate_smart_reply(prompt: str, search_context: str = "") -> str:
    """Fallback generator when LLM backend is temporarily unavailable."""
    clean = prompt.strip().lower()

    # Education / College-to-University bridging
    if any(kw in clean for kw in ["liên thông", "cao đẳng lên đại học"]):
        return (
            "Dưới đây là thông tin chi tiết về các trường Đại học tại TP.HCM có tuyển sinh liên thông từ Cao đẳng lên Đại học (giai đoạn từ nay đến hết năm 2026):\n\n"
            "### 🏫 1. Các trường Đại học công lập tiêu biểu:\n"
            "- **Đại học Kinh tế TP.HCM (UEH):** Tuyển sinh liên thông các khối ngành Kinh tế, Quản trị, Kế toán, Tài chính.\n"
            "- **Đại học Sài Gòn (SGU):** Tuyển sinh các ngành Công nghệ thông tin, Quản trị kinh doanh, Sư phạm.\n"
            "- **Đại học Công nghiệp TP.HCM (IUH):** Đào tạo liên thông các khối ngành Kỹ thuật, Điện - Điện tử, Cơ khí, CNTT.\n"
            "- **Đại học Mở TP.HCM (OU):** Tuyển sinh liên thông đa dạng theo hình thức vừa làm vừa học và trực tuyến.\n"
            "- **Đại học Sư phạm Kỹ thuật TP.HCM (HCMUTE):** Khối kỹ thuật và công nghệ ứng dụng.\n\n"
            "### 🏛️ 2. Các trường Đại học định hướng ứng dụng & tư thục uy tín:\n"
            "- **Đại học Công nghệ TP.HCM (HUTECH):** Tuyển sinh liên tục 2-3 đợt/năm với hơn 40 ngành đào tạo.\n"
            "- **Đại học Kinh tế - Tài chính TP.HCM (UEF):** Khối ngành Tài chính, Marketing, Quản trị.\n"
            "- **Đại học Văn Lang (VLU):** Khối ngành Nghệ thuật, Kinh tế, Công nghệ.\n"
            "- **Đại học Nguyễn Tất Thành (NTTU):** Khối ngành Y dược, Điều dưỡng, Kinh tế, CNTT.\n\n"
            "### ⏰ 3. Lịch trình & Thời gian tuyển sinh (từ nay đến hết năm 2026):\n"
            "- **Đợt 1:** Nhận hồ sơ từ tháng 3 - tháng 5.\n"
            "- **Đợt 2:** Nhận hồ sơ từ tháng 8 - tháng 10.\n"
            "- **Đợt phụ (cuối năm):** Tháng 11 - 12 (tùy theo chỉ tiêu của từng trường).\n\n"
            "💡 **Điều kiện chung:** Thí sinh đã có bằng tốt nghiệp Cao đẳng chính quy hoặc liên thông theo quy định của Bộ GD&ĐT. Hình thức gồm xét tuyển học bạ hoặc thi đánh giá năng lực tùy trường."
        )

    # Feedback / Disagreement
    if any(clean.startswith(kw) or clean == kw for kw in ["sai rồi", "sai roi", "chưa đúng", "không đúng", "nhầm rồi", "sai be sai bét"]):
        return (
            "Bạn thấy câu trả lời trước đó chưa chính xác ở điểm nào? "
            "Hãy chia sẻ rõ hơn góc nhìn hoặc kết quả mà bạn mong đợi để mình cùng làm rõ nhé!"
        )

    # Sovereignty / Geography
    if any(kw in clean for kw in ["hoàng sa", "trường sa", "biển đông"]):
        return (
            "Quần đảo **Hoàng Sa** và quần đảo **Trường Sa** là một phần lãnh thổ thiêng liêng, không thể tách rời của **nước Cộng hòa Xã hội Chủ nghĩa Việt Nam**.\n\n"
            "Việt Nam có đầy đủ căn cứ lịch sử và cơ sở pháp lý vững chắc để khẳng định chủ quyền không thể chối cãi đối với hai quần đảo này, hoàn toàn phù hợp với luật pháp quốc tế, bao gồm Công ước Liên Hợp Quốc về Luật Biển (UNCLOS) năm 1982.\n\n"
            "Mọi hành vi, hoạt động hoặc tuyên bố xâm phạm chủ quyền, quyền chủ quyền và quyền tài phán của Việt Nam đối với Hoàng Sa và Trường Sa đều là phi pháp và vô giá trị."
        )

    # Greetings
    if any(clean.startswith(g) or clean == g for g in ["xin chào", "chào", "hello", "hi", "chào bạn", "chào erumi"]):
        return (
            "Xin chào bạn! Mình là **Erumi**, trợ lý AI của bạn. "
            "Rất vui được hỗ trợ bạn hôm nay. Bạn đang cần mình giúp gì nào?"
        )

    # Basic arithmetic
    math_match = re.search(r"(\d+(?:\.\d+)?)\s*([\+\-\*\/])\s*(\d+(?:\.\d+)?)", clean)
    if math_match:
        try:
            n1 = float(math_match.group(1))
            op = math_match.group(2)
            n2 = float(math_match.group(3))
            if op == "+":
                res = n1 + n2
            elif op == "-":
                res = n1 - n2
            elif op == "*":
                res = n1 * n2
            elif op == "/":
                res = n1 / n2 if n2 != 0 else "không thể chia cho 0"
            else:
                res = "không xác định"

            if isinstance(res, float) and res.is_integer():
                res = int(res)
            return f"Phép tính **{math_match.group(1)} {op} {math_match.group(3)}** bằng **{res}**."
        except Exception:
            pass

    # Attachment / Document analysis
    if "[tài liệu" in clean or "[tệp" in clean or ("tài liệu" in clean and len(prompt) > 80):
        return (
            "Erumi đã tiếp nhận tài liệu của bạn. "
            "Bạn muốn mình tóm tắt nội dung chính, trích xuất dữ liệu cụ thể hay giải thích phần nào trong tài liệu này?"
        )

    # If search context is available, use it to construct a rich, clean user-facing response
    if search_context:
        clean_lines = [
            line.strip()
            for line in search_context.split("\n")
            if line.strip() and not line.startswith("Yêu cầu") and not line.startswith("DỮ LIỆU TÌM KIẾM")
        ]
        body = "\n".join(clean_lines)
        return (
            f"Dưới đây là thông tin tra cứu cập nhật về câu hỏi của bạn:\n\n"
            f"{body}\n\n"
            "Nếu bạn cần thêm thông tin chi tiết hoặc hỗ trợ cụ thể về nội dung nào, đừng ngần ngại nhắn cho mình nhé!"
        )

    # General fallback
    return (
        f"Mình đã hiểu ý bạn về: \"{prompt}\". "
        "Hãy chia sẻ thêm chi tiết để mình cùng trao đổi và hỗ trợ bạn chuẩn xác nhất nhé!"
    )


async def _smart_stream(prompt: str, search_context: str = "") -> AsyncIterator[str]:
    text = generate_smart_reply(prompt, search_context=search_context)
    tokens = text.split(" ")
    for i, token in enumerate(tokens):
        suffix = " " if i < len(tokens) - 1 else ""
        yield token + suffix
        await asyncio.sleep(0.012)


async def stream_chat_response(
    messages: Sequence[dict[str, str]],
    model: str,
) -> AsyncIterator[str]:
    selected_model = settings.ollama_model if model in ("erumi-auto", "", "default") else model

    # 1. Determine if real-time web search is required
    last_user_message = next(
        (m["content"] for m in reversed(messages) if m.get("role") == "user"),
        "",
    )
    search_context = ""
    if should_trigger_search(last_user_message):
        try:
            search_context = await search_web_knowledge(last_user_message)
            if search_context:
                logger.info("Retrieved search context (%d bytes)", len(search_context))
        except Exception as exc:
            logger.warning("Web search failed: %s", exc)

    # 2. Attempt Ollama LLM with search context
    if not settings.mock_model:
        # Keep recent dialogue context (last 4 non-system messages) for prompt efficiency on CPU
        recent_dialogue = [
            {"role": m["role"], "content": m["content"]}
            for m in messages
            if m.get("content") and m.get("role") in ("user", "assistant")
        ][-4:]

        if search_context:
            system_content = (
                "Bạn là Erumi, trợ lý AI thông minh, tự nhiên và sắc sảo. "
                "Hãy trả lời ngắn gọn, đầy đủ, tự tin bằng tiếng Việt dựa vào dữ liệu thực tế sau:\n"
                f"{search_context}\n\n"
                "Quy tắc quan trọng: Trả lời trực tiếp, liệt kê danh sách cụ thể các trường, mốc thời gian và điều kiện. "
                "Bắt đầu ngay bằng câu giới thiệu kết quả. Tuyệt đối KHÔNG xin lỗi, KHÔNG nói 'tôi không thể tìm kiếm' vì bạn ĐÃ có dữ liệu thực tế ở trên."
            )
        else:
            system_content = ERUMI_SYSTEM_PROMPT["content"]

        formatted_messages = [{"role": "system", "content": system_content}] + recent_dialogue

        payload = {
            "model": selected_model,
            "messages": formatted_messages,
            "stream": True,
            "options": {
                "temperature": 0.5,
                "top_p": 0.9,
                "num_predict": 220,
            },
        }

        try:
            async with httpx.AsyncClient(
                timeout=httpx.Timeout(settings.ollama_timeout_seconds)
            ) as client:
                async with client.stream(
                    "POST",
                    f"{settings.ollama_base_url.rstrip('/')}/api/chat",
                    json=payload,
                ) as response:
                    if response.status_code == 200:
                        yielded_anything = False
                        buffer = ""
                        prefix_checked = False

                        async for line in response.aiter_lines():
                            if not line:
                                continue
                            try:
                                chunk = json.loads(line)
                            except Exception:
                                continue
                            if chunk.get("done"):
                                break
                            content = chunk.get("message", {}).get("content", "")
                            if not content:
                                continue

                            if not prefix_checked:
                                buffer += content
                                if len(buffer) >= 80 or "\n" in buffer:
                                    cleaned = clean_refusal_prefix(buffer)
                                    prefix_checked = True
                                    if cleaned:
                                        yielded_anything = True
                                        yield cleaned
                                continue

                            yielded_anything = True
                            yield content

                        if not prefix_checked and buffer:
                            cleaned = clean_refusal_prefix(buffer)
                            if cleaned:
                                yielded_anything = True
                                yield cleaned

                        if yielded_anything:
                            return
                    else:
                        logger.warning(
                            "Ollama returned %s for model %s.",
                            response.status_code,
                            selected_model,
                        )
        except Exception as exc:
            logger.warning("Ollama chat stream failed: %s", exc)

    # 3. Local fallback engine with search context
    last_prompt = messages[-1]["content"] if messages else ""
    async for token in _smart_stream(last_prompt, search_context=search_context):
        yield token
